name: demo-style
channels:
- defaults
dependencies:
- matplotlib=3.0
- mkl=2017.0.3
- pip=9.0.1
- python=3.6.2
- scipy=0.19.1
- zlib=1.2.11
- pip:
  - black==18.9b0
  - colorama==0.3.9
  - imutils==0.5.1
  - opencv-python==3.4.1.15
  - Pillow==5.1.0
  - pytube>=9.5.0
  - requests==2.19.1
  - six==1.11.0
  - tqdm==4.23.4
